---
title: "Case study and report format"
author: "Data Science Final Report Format"
date: "Spring 2019"
output: pdf_document
---

Case Study format
Found in James Cochrane, Analytics Body of Knowledge

# Section 1 – Overview

Review the scenario and context. Identify the problem(s) to be addressed.
Discuss the important players and stakeholders and their interests and motivations. Assume you are employed as an analyst for the organization in the case.  Context, Need.

#	Section 2 - Methodology

Explain and justify the approach(es) that you propose to use in addressing the
problem(s)/ responding to the question(s) suggested by the case. Discuss any
assumptions (mathematical or otherwise) that you are making, and explain
the consequences that could arise if your assumptions are invalid. If appropriate, explain why other approaches under consideration are inferior or unsuitable. Use nontechnical terms that someone with a minimal background in operations research can understand.  Vision

#	Section 3 - Results

Present and interpret the results. Explain the potential implications of the
analysis. Include graphs, displays, calculations, or printouts if appropriate, or
place them in appendices and refer to them in this section. Do not include
graphs, displays, calculations, or printouts if they do not provide illumination.
Suggest a decision or a strategy if appropriate. If possible, discuss issues that
may arise in implementation of the suggested decision or strategy. Be creative
and use intuition. Outcome

#	Section 4 - Critical Assessment

Examine the approaches to data collection and analysis. Discuss positive and
negative aspects of this process. Suggest (i) ways to improve the analytic
process you just completed and (ii) directions for future analysis.

#	Appendices-Relevant Printouts, Tables, and Graphics

Results and displays may be placed in appendices. Note that appendices
should be numbered and appropriately labeled, and each appendix should be referred to at least once in the body of the case analysis.


# Notes:

-	Other than in Methodology, use nontechnical terms that someone with a minimal background in statistics or operations research can understand.  I.e. a client that does not have a graduate degree in engineering.
-	Avoid discussions of the mechanics of the solution algorithm or software used in the analysis.  i.e. Name methods and algorithms.  Software packages and programming languages are the environment you implement your methods in.
-	Resist the temptation to review or critique the teaching case (this is not the place for the student to explain how she or he feels about the assignment).

