---
title: 'Homework 2: Regression'
author: "IE 2064 Data Science"
date: "March 7, 2019"
output:
  html_document: default
  pdf_document: default
---


**CHANGE Due Wednesday March 6, 2019**

Note: Your dataset from EDA is probably naturally either a regression problem or a classification problem.  So you do not necessarily need to use the same dataset for this assignment as the EDA dataset if it is unrealistic for a regression problem.

1.  Identify a data set from Applied Predictive Models (APM) Chapter 1.4.
2.  Identify a variable that you will attempt to predict using regression.
    i. Name
    ii. Short, one sentence description
    iii. Description of potential values (include data type and units)
    iv. mean, median, quartiles, range if applicable
    v. histogram/density plot
3.  A hypothetical CoNVO statement.  Note: if this is not the natural problem setting that you identified in homework 1 (i.e. you really have a classification problem), state this. Your CoNVO statement for this assignment can potentially be very unrealistic in this case.
4.  Use 10 fold cross validation with one model from each of the following categories to:

        1.  Determine the correct complexity of the model.
        2.  Compare each using Root mean square error.
    i.  Linear modesl
        1.  Linear regression,
        2.  Lasso
        3.  Ridge regresssion
    ii.  Trees
        1.  Regression tree
        2.  Naive Bayes
    iv. Non-linear models
        1.  Support Vector Machines (SVM)
        2.  Neural Nets
        3.  Multivariate Adaptive Regression Splines (MARS)
        4.  K-nearest Neighbors (KNN)
    v. Ensemble methods
        1.  Random forests
        2.  Boosting
        3.  Cubist

6.  Reflection.  Which category (of the four you used) is the best for this problem and why.
