---
title: 'Homework 3: Classification'
author: "IE 2064 Data Science"
date: "March 21, 2018"
output:
  pdf_document: default
  html_document: default
---

**Due Wednesday March 21, 2018**

Note: Your dataset from EDA is probably naturally either a regression problem or a classification problem.  So you do not necessarily need to use the same dataset for this assignment as the EDA dataset.

1.  Identify a data set from Applied Predictive Models (APM) Chapter 1.4.
2.  Identify a variable that you will attempt to predict using classification
    i. Name
    ii. Short, one sentence description
    iii. Description of potential values (include data type and units)
    iv. Histogram plot
3.  A hypothetical CoNVO statement.  Note: if this is not the natural problem setting that you identified in homework 1 (i.e. you really have a classification problem), state this. Your CoNVO statement for this assignment can potentially be very unrealistic in this case.
4.  For Classification trees and one of:

4.  Use 10 fold cross validation with one model from each of the following categories to:

        1.  Determine the correct complexity of the model.
        2.  Compare each showing the Receiver Operating Characteristic (ROC) curve for that model and AUC.
        3.  Construct a lift chart.
    i.  Linear models  
        1.  Logistic regression,
        2.  Linear discriminant analysis
        3.  Partial least squares discriminant analysis
        4.  Penalized models
    ii.  Trees
        1.  Classification trees
        2.  Naive Bayes
    iII.  Non-linear models
        1.  Support Vector Machines (SVM)
        2.  Neural Nets
        3.  Non-linear discriminant analysis
        4.  K-nearest Neighbors (KNN)
    iv.  Ensemble methods
        4.  Random forests
        5.  Boosting
        6.  Cubist

6.  Reflection.  Which category is the best for this problem and why.
